export const SET_SEARCH_DATA = 'SET_SEARCH_DATA';

export const SET_SEARCH_POSTS = 'SET_SEARCH_POSTS';

export const LOAD_SEARCH_POSTS = 'LOAD_SEARCH_POSTS';

export const SET_SEARCH_SUGGEST = 'SET_SEARCH_SUGGEST';

export const SET_SEARCH_HOTWORD = 'SET_SEARCH_HOTWORD';

export const SET_SEARCH_LOADING = 'SET_SEARCH_LOADING';


