export const SET_GAMELIST = 'SET_GAMELIST';

export const SET_CHANNELLIST = 'SET_CHANNELLIST';

export const SET_RECOMMENDED_POSTS = 'SET_RECOMMENDED_POSTS';

export const SET_HOME_POSTID_STAT = 'SET_HOME_POSTID_STAT';

export const SET_HOME_LOADING = 'SET_HOME_LOADING';

export const SET_HOME_NAV = 'SET_HOME_NAV';

export const SET_HOME_DISCUSSION = 'SET_HOME_DISCUSSION';

export const SET_HOME_OFFICIAL = 'SET_HOME_OFFICIAL';

export const SET_HOME_BACKGROUND = 'SET_HOME_BACKGROUND';

export const SET_HOME_CAROUSELS = 'SET_HOME_CAROUSELS';

export const SET_HOME_HOTTOPICS = 'SET_HOME_HOTTOPICS';

export const LOAD_RECOMMENDED_POSTS = 'LOAD_RECOMMENDED_POSTS';